src/Otus.Teaching.Pcf.App/Pages/Administration/Customers/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using Otus.Teaching.Pcf.App.Utils.Client;
using Otus.Teaching.Pcf.App.Utils.Settings;
using Otus.Teaching.Pcf.GivingToCustomer.WebHost.Models;

namespace Otus.Teaching.Pcf.App.Pages.Administration.Customers
{
    public class IndexModel : PageModel
    {
        private AppSettings AppSettings { get; }
        private HttpClient HttpClient { get; }

        public IndexModel(IOptions<AppSettings> appSettings)
        {
            HttpClient = new HttpClient();
            this.AppSettings = appSettings.Value;

            HttpClient.BaseAddress = new Uri(this.AppSettings.AddressSeverCustomer);
            HttpClient.DefaultRequestHeaders.Add("User-Agent", "Server");
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<List<CustomerShortResponse>> GetCustomerAllAsync()
        {
            return await new WebClient<CustomerShortResponse>(HttpClient).GetAllAsync(AppSettings.AddressSeverCustomer + "Customers");
        }
       
        public async Task<CreateOrEditCustomerRequest> GetCustomerAsync(string Id) 
        {
            return await new WebClient<CreateOrEditCustomerRequest>(HttpClient).GetCustomerAsync(Guid.Parse(Id), AppSettings.AddressSeverCustomer + "Customers");
        }

        public  List<PreferenceResponse> GetResponseAllAsync()
        {
            return new WebClient<PreferenceResponse>(HttpClient).GetAllAsync(AppSettings.AddressSeverCustomer + "Preferences").Result.ToList<PreferenceResponse>();
        }

        public async Task<IActionResult> OnPostSubmit(CreateOrEditCustomerRequest customerRequest)
        {
            await new WebClient<CreateOrEditCustomerRequest>(HttpClient).Create(customerRequest, AppSettings.AddressSeverCustomer + "Customers");

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDeleteAsync(Guid Id)
        {
            await new WebClient<Guid>(HttpClient).Delete(Id, AppSettings.AddressSeverCustomer + "Delete");

            return RedirectToPage();
        }

        public JsonResult OnPost(string Id)
        {
            var Customer = new WebClient<CustomerResponse>(HttpClient).GetCustomerAsync(Guid.Parse(Id), AppSettings.AddressSeverCustomer + "Customers").Result;
            
            string json = Newtonsoft.Json.JsonConvert.SerializeObject(Customer);

            return new JsonResult(json);
        }

        public async  Task<IActionResult> OnPostEdit(Guid Id, CreateOrEditCustomerRequest customerResponse)
        {
            await new  WebClient<CreateOrEditCustomerRequest>(HttpClient).UpdateAsync(Id, customerResponse, AppSettings.AddressSeverCustomer + "Customers");

            return RedirectToPage();
        }
    }
}

src/Otus.Teaching.Pcf.App/Pages/Administration/Preference.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using Otus.Teaching.Pcf.App.Utils.Client;
using Otus.Teaching.Pcf.App.Utils.Settings;
using Otus.Teaching.Pcf.GivingToCustomer.WebHost.Models;

namespace Otus.Teaching.Pcf.App.Pages.Administration
{
    public class PreferenceModel : PageModel
    {
        private AppSettings AppSettings { get; }
        private HttpClient HttpClient { get; }

        public PreferenceModel(IOptions<AppSettings> appSettings)
        {
            HttpClient = new HttpClient();
            this.AppSettings = appSettings.Value;

            HttpClient.BaseAddress = new Uri(this.AppSettings.AddressSever);
            HttpClient.DefaultRequestHeaders.Add("User-Agent", "Server");
        }

        public void OnGet()
        {
        }

        public async Task<List<PreferenceResponse>> GetAllAsync()
        {
            return await new WebClient<PreferenceResponse>(HttpClient).GetAllAsync(AppSettings.AddressSever + "Preferences");
        }
    }
}

src/Otus.Teaching.Pcf.App/Pages/Administration/Preference/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using Otus.Teaching.Pcf.App.Utils.Client;
using Otus.Teaching.Pcf.App.Utils.Settings;
using Otus.Teaching.Pcf.GivingToCustomer.WebHost.Models;

namespace Otus.Teaching.Pcf.App.Pages.Administration
{
    public class PreferenceModel : PageModel
    {
        private AppSettings AppSettings { get; }
        private HttpClient HttpClient { get; }

        public PreferenceModel(IOptions<AppSettings> appSettings)
        {
            HttpClient = new HttpClient();
            this.AppSettings = appSettings.Value;

            HttpClient.BaseAddress = new Uri(this.AppSettings.AddressSeverCustomer);
            HttpClient.DefaultRequestHeaders.Add("User-Agent", "Server");
        }

        public void OnGet()
        {
        }

        public async Task<List<PreferenceResponse>> GetAllAsync()
        {
            return await new WebClient<PreferenceResponse>(HttpClient).GetAllAsync(AppSettings.AddressSeverCustomer + "Preferences");
        }
    }
}

src/Otus.Teaching.Pcf.App/Pages/Administration/Promocodes/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using Otus.Teaching.Pcf.Administration.WebHost.Models;
using Otus.Teaching.Pcf.App.Utils.Client;
using Otus.Teaching.Pcf.App.Utils.Settings;
using Otus.Teaching.Pcf.ReceivingFromPartner.WebHost.Models;

namespace Otus.Teaching.Pcf.App.Pages.Administration.promocodes
{
    public class IndexModel : PageModel
    {
        private AppSettings AppSettings { get; }
        private HttpClient HttpClient { get; }

        public IndexModel(IOptions<AppSettings> appSettings)
        {
            HttpClient = new HttpClient();
            this.AppSettings = appSettings.Value;

            HttpClient.BaseAddress = new Uri(this.AppSettings.AddressSeverPartner);
            HttpClient.DefaultRequestHeaders.Add("User-Agent", "Server");
        }
        public void OnGet()
        {
        }

        public List<PreferenceResponse> GetResponseAllAsync()
        {
            return new WebClient<PreferenceResponse>(HttpClient).GetAllAsync(AppSettings.AddressSeverPartner + "Partners").Result.ToList<PreferenceResponse>()
;
        }   
        
        public async Task<List<PreferenceResponse>> GetPreferenceIdAllAsync()
        {
            return await new WebClient<PreferenceResponse>(HttpClient).GetAllAsync(AppSettings.AddressSeverCustomer + "Preferences");
        }

        public List<EmployeeShortResponse> GetEmployeesAllAsync()
        {
            return new WebClient<EmployeeShortResponse>(HttpClient).GetAllAsync(AppSettings.AddressSeverAdministration + "Employees").Result.ToList<EmployeeShortResponse>();
        }

        public async void OnPostSubmit(Guid Id, ReceivingPromoCodeRequest request)
        {
            await new WebClient<ReceivingPromoCodeRequest>(HttpClient).CreatePromo(Id, request, AppSettings.AddressSeverPartner + "Partners");
        }

        public  List<PromoCodeShortResponse> GetAllPromocodesAsync()
        {
            return  new WebClient<PromoCodeShortResponse>(HttpClient).GetAllAsync(AppSettings.AddressSeverCustomer + "Promocodes").Result.ToList<PromoCodeShortResponse>();
        }
    }
}

src/Otus.Teaching.Pcf.App/Pages/Administration/Customers/Index.cshtml
@page

@model Otus.Teaching.Pcf.App.Pages.Administration.Customers.IndexModel

@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Xsrf
@functions{
    public string GetAntiXsrfRequestToken()
    {
        return Xsrf.GetAndStoreTokens(Model.HttpContext).RequestToken;
    }
}

@using Otus.Teaching.Pcf.GivingToCustomer.WebHost.Models;

<div>
    <button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#Crete">Добавить</button>
    <br>
    <br>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    @Html.DisplayName("Имя")
                </th>
                <th>
                    @Html.DisplayName("Фамилия")
                </th>
                <th>
                    @Html.DisplayName("Email")
                </th>
                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.GetCustomerAllAsync().Result.ToList<CustomerShortResponse>())
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        <form method="post">
                            <input type="button" class="btn btn-secondary btn-sm" onclick="GetCutomer('@item.Id')" value="Редактировать" />
                            <button id="myModalEditBtn" type="submit" class="btn btn-danger btn-sm" asp-page-handler="delete" asp-route-id="@item.Id">Удалить</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="modal fade" id="Crete" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Добавление</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form class="was-validated" method="post">

                    <label for="firstName">Имя:</label>
                    <input type="text" class="form-control is-invalid" name="firstName" aria-describedby="firstName" required>

                    <label for="lastName">Фамилия:</label>
                    <input type="text" class="form-control" name="lastName" aria-describedby="lastName" required>

                    <label for="Email">Email:</label>
                    <input type="email" class="form-control" name="Email" aria-describedby="email" required>

                    <label for="PreferenceIds">Предпочтения</label>

                    <select name="PreferenceIds" class="form-control" required>
                        @foreach (var item in Model.GetResponseAllAsync())
                        {
                            <option id="@item.Id" value="@item.Id">@item.Name</option>
                        }
                    </select>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                        <button type="submit" class="btn btn-primary" asp-page-handler="Submit">Сохранить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="Edit" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Редактирование</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form class="was-validated" method="post">
                    <input id="Id" class="form-control is-invalid" name="Id" aria-describedby="Id" required>
                    <label for="firstName">Имя:</label>
                    <input id="FirstName" class="form-control is-invalid" name="FirstName" aria-describedby="FirstName" required>
                    <label for="lastName">Фамилия:</label>
                    <input id="LastName" class="form-control" name="LastName" aria-describedby="LastName" required>
                    <label for="Email">Email:</label>
                    <input id="Email" class="form-control" name="Email" aria-describedby="Email" required>
                    <label for="Preferences">Предпочтения</label>
                    <br>
                    @foreach (var item in Model.GetResponseAllAsync())
                    {
                        <input name="PreferenceIds" type="checkbox" id="@item.Name" value="@item.Id">@item.Name<br />

                    }
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                        <button type="submit" class="btn btn-primary" asp-page-handler="Edit">Сохранить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>

    function GetCutomer(Id) {
        $.ajax({
            url: "/Administration/Customers/",
            dataType: "json",
            headers: { "RequestVerificationToken": $('input:hidden[name="__RequestVerificationToken"]').val() },
            type: "POST",
            data: { "Id": Id },
            success: function (data) {
                var obj = JSON.parse(data);
                document.getElementById("Id").value = obj.Id;
                document.getElementById("FirstName").value = obj.FirstName;
                document.getElementById("LastName").value = obj.LastName;
                document.getElementById("Email").value = obj.Email;

                for (i in obj.Preferences) {
                    document.getElementById(obj.Preferences[i].Name).checked = true;
                }

                $('#Edit').modal('show');
            },
            error: function (xhr) {
            }
        });

        var hideView = function () {
            $('#Edit').modal('hide');
        }
    }

    function Save(Id, FirstName, LastName, Email) {
        $.ajax({
            url: "/Administration/Customers/",
            dataType: "json",
            headers: { "RequestVerificationToken": $('input:hidden[name="__RequestVerificationToken"]').val() },
            type: "get",
            data: {
                "Id": Id,
                "FirstName": FirstName,
                "LastName": LastName,
                "Email": Email
            },
            success: function (data) {
            },
        });
    }
</script>